### ISSUE TITLE
Clarifying licensing

### ISSUE THREAD

**Issue by aravind-pg** [NLPrinceton/text_embedding#1]
We were interested in using code from this repository and saw that it does not explicitly include a license. Would the authors be open to adding one? We see that https://github.com/NLPrinceton/SARC is MIT-licensed and builds off of this, so something like that would be perfect. Appreciate your time.

cc @mkhodak

**Comment by nsaunshi** [comment]
Thanks for pointing out. We added an MIT license.

**Comment by aravind-pg** [comment]
Thanks a lot!
